version: "3"
services:
  node2:
    build: .
    image: nodeimg
    container_name: node2
    volumes:
      - ${PWD}/node2Config.yaml:/app/config.yaml
    ports:
      - 8002:8002
      - 8003:8003
    network_mode: "host"

  node3:
    image: nodeimg
    container_name: node3
    volumes:
      - ${PWD}/node3Config.yaml:/app/config.yaml
    ports:
      - 8004:8004
      - 8005:8005
    network_mode: "host"

  node1:
    image: nodeimg
    container_name: node1
    volumes:
      - ${PWD}/node1Config.yaml:/app/config.yaml
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - node2
      - node3
    command:
      [
        "/bin/bash",
        "-c",
        "sleep 5 && go run . --configPath=config.yaml"
      ]
    network_mode: "host"

  node4:
    image: nodeimg
    container_name: node4
    volumes:
      - ${PWD}/node4Config.yaml:/app/config.yaml
    ports:
      - 8006:8006
      - 8007:8007
    depends_on:
      - node1
    command:
      [
        "/bin/bash",
        "-c",
        "sleep 10 && go run . --configPath=config.yaml"
      ]
    network_mode: "host"
